import type { Level, Room } from './types';

/**
 * Daily puzzle. The theme is hidden — the payoff is the meta answer, spelled by
 * the blue letters. Generated by scripts/genPuzzle.mjs.
 */

const rooms: Room[] = [
  {
    id: 'r0',
    clue: 'Thief who works a crowd',
    answer: 'PICKPOCKET',
    next: ['r3'],
    row: 0,
    col: 1,
  },
  {
    id: 'r1',
    clue: 'Tough penal sentence',
    answer: 'HARDLABOUR',
    enumeration: [4, 6],
    next: ['r3', 'r5'],
    row: 0,
    col: 3,
    powerUp: 'reveal',
  },
  {
    id: 'r2',
    clue: 'Place of confinement',
    answer: 'PRISON',
    next: ['r4'],
    row: 0,
    col: 5,
  },
  {
    id: 'r3',
    clue: 'Place where goods are bought and sold',
    answer: 'MARKET',
    next: ['r7', 'r8'],
    row: 1,
    col: 1,
    metaLetterIndex: 5, // T
  },
  {
    id: 'r4',
    clue: 'Police officer of the lowest rank',
    answer: 'CONSTABLE',
    next: ['r8'],
    row: 1,
    col: 3,
  },
  {
    id: 'r5',
    clue: 'Giving to those in need',
    answer: 'CHARITY',
    next: ['r6'],
    row: 1,
    col: 5,
    metaLetterIndex: 5, // T
  },
  {
    id: 'r6',
    clue: 'Tall formal headwear',
    answer: 'TOPHAT',
    enumeration: [3, 3],
    next: ['r9', 'r10'],
    row: 2,
    col: 1,
  },
  {
    id: 'r7',
    clue: 'Stiff undergarment that cinches the waist',
    answer: 'CORSET',
    next: ['r9', 'r11'],
    row: 2,
    col: 3,
  },
  {
    id: 'r8',
    clue: 'Pot for boiling water',
    answer: 'KETTLE',
    next: ['r9', 'r11'],
    row: 2,
    col: 5,
    metaLetterIndex: 4, // L
  },
  {
    id: 'r9',
    clue: 'Timepiece carried on a chain',
    answer: 'POCKETWATCH',
    enumeration: [6, 5],
    next: ['r14'],
    row: 3,
    col: 1,
    metaLetterIndex: 6, // W
  },
  {
    id: 'r10',
    clue: 'A local judge',
    answer: 'MAGISTRATE',
    next: ['r12'],
    row: 3,
    col: 3,
  },
  {
    id: 'r11',
    clue: 'Minor stealing charge',
    answer: 'PETTYTHEFT',
    enumeration: [5, 5],
    next: ['r13'],
    row: 3,
    col: 5,
  },
  {
    id: 'r12',
    clue: 'One who carries luggage',
    answer: 'PORTER',
    next: ['r17'],
    row: 4,
    col: 1,
  },
  {
    id: 'r13',
    clue: 'Brimmed hat tied under the chin; or a car\'s hood',
    answer: 'BONNET',
    next: ['r15'],
    row: 4,
    col: 3,
    powerUp: 'reveal',
  },
  {
    id: 'r14',
    clue: 'Soot-clearing tradesman',
    answer: 'CHIMNEYSWEEP',
    enumeration: [7, 5],
    next: ['r16'],
    row: 4,
    col: 5,
    metaLetterIndex: 7, // S
  },
  {
    id: 'r15',
    clue: 'Ragged child of the city',
    answer: 'STREETURCHIN',
    enumeration: [6, 6],
    next: ['r19'],
    row: 5,
    col: 1,
    metaLetterIndex: 3, // E
  },
  {
    id: 'r16',
    clue: 'A criminal\'s career',
    answer: 'LIFEOFCRIME',
    enumeration: [4, 2, 5],
    next: ['r18'],
    row: 5,
    col: 3,
    metaLetterIndex: 7, // R
  },
  {
    id: 'r17',
    clue: 'Of Queen Victoria\'s reign',
    answer: 'VICTORIAN',
    next: ['r20'],
    row: 5,
    col: 5,
    metaLetterIndex: 4, // O
  },
  {
    id: 'r18',
    clue: 'A high temperature with illness',
    answer: 'FEVER',
    next: ['r21'],
    row: 6,
    col: 1,
    metaLetterIndex: 2, // V
  },
  {
    id: 'r19',
    clue: 'A pub, more formally',
    answer: 'PUBLICHOUSE',
    enumeration: [6, 5],
    next: ['r21', 'r22'],
    row: 6,
    col: 3,
    metaLetterIndex: 4, // I
  },
  {
    id: 'r20',
    clue: 'The bad guy of a story',
    answer: 'VILLAIN',
    next: ['r22'],
    row: 6,
    col: 5,
  },
  {
    id: 'r21',
    clue: 'A household employee',
    answer: 'SERVANT',
    next: ['r23'],
    row: 7,
    col: 2,
    powerUp: 'vowel',
  },
  {
    id: 'r22',
    clue: 'Another portion at dinner',
    answer: 'SECONDHELPING',
    enumeration: [6, 7],
    next: ['r23'],
    row: 7,
    col: 4,
    metaLetterIndex: 10, // I
  },
  {
    id: 'r23',
    clue: 'A travelling mender of pots',
    answer: 'TINKER',
    next: [],
    row: 8,
    col: 3,
    isFinal: true,
  },
];

export const OLIVER: Level = {
  id: 'daily-2026-06-23',
  date: '2026-06-23',
  difficulty: 'Medium',
  title: 'Tuesday 23 June',
  subtitle: 'Solve a path to the top, then crack the hidden meta.',
  rooms,
  startRoomIds: ['r0', 'r1', 'r2'],
  finalRoomId: 'r23',
  meta: {
    answer: 'OLIVERTWIST',
    enumeration: [6, 5],
    prompt:
      'No clue, no theme given \u2014 only the eleven blue letters you gathered along the way. Rearrange them into the two words they spell. (6,5)',
    hint: 'Two words, eleven letters \u2014 together they name what this whole maze has quietly been about.',
  },
};

export const PUZZLES: Level[] = [OLIVER];
export const LEVELS: Level[] = PUZZLES;
